version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build: ./php-fpm
    volumes:
      - ./src:/var/www/html
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
